18:30:09,97 asyncio DEBUG Using selector: KqueueSelector
18:30:09,115 docker.api.build DEBUG Looking for auth config
18:30:09,453 docker.auth DEBUG Looking for auth entry for 'https://docker.io'
18:30:09,801 docker.auth DEBUG Looking for auth entry for 'https://index.docker.io/v1/'
18:30:10,97 asyncio DEBUG Using selector: KqueueSelector
18:30:10,152 docker.auth DEBUG Looking for auth entry for 'https://index.docker.io/v1//access-token'
18:30:10,578 docker.auth DEBUG Looking for auth entry for 'https://index.docker.io/v1//refresh-token'
18:30:10,931 docker.api.build DEBUG Sending auth config ('docker.io', 'https://index.docker.io/v1/', 'https://docker.io', 'index.docker.io', 'https://index.docker.io/v1//access-token', 'https://index.docker.io/v1//refresh-token')
18:30:10,964 urllib3.connectionpool DEBUG http://localhost:None "POST /v1.43/build?t=mptest02-test%3A1.0.0&q=False&nocache=False&rm=True&forcerm=False&pull=False&labels=%7B%22mp-test%22%3A+%221686155409.08296%22%7D HTTP/1.1" 200 None
18:30:11,42 urllib3.connectionpool DEBUG http://localhost:None "GET /v1.43/images/dba5c8e98e18/json HTTP/1.1" 200 None
18:30:11,67 urllib3.connectionpool DEBUG http://localhost:None "POST /v1.43/containers/create HTTP/1.1" 201 None
18:30:11,72 urllib3.connectionpool DEBUG http://localhost:None "GET /v1.43/containers/0965a5c10288bfc9e71acd8b537f57e846ac72e418bd8188b0af011668a45154/json HTTP/1.1" 200 None
18:30:11,306 urllib3.connectionpool DEBUG http://localhost:None "POST /v1.43/containers/0965a5c10288bfc9e71acd8b537f57e846ac72e418bd8188b0af011668a45154/start HTTP/1.1" 204 0
18:30:11,391 asyncio DEBUG Using selector: KqueueSelector
18:30:13,55 httpx._client DEBUG HTTP Request: GET http://localhost:8080/apiVersion "HTTP/1.1 200 OK"
18:30:14,146 urllib3.connectionpool DEBUG http://localhost:None "GET /v1.43/containers/0965a5c10288bfc9e71acd8b537f57e846ac72e418bd8188b0af011668a45154/stats?stream=False HTTP/1.1" 200 None
18:30:14,765 httpx._client DEBUG HTTP Request: GET http://localhost:8080/adapterDefinition "HTTP/1.1 500 INTERNAL SERVER ERROR"
18:30:14,770 vmware_aria_operations_integration_sdk.describe ERROR 500 INTERNAL SERVER ERROR
No result from adapter. Captured stderr:
  Traceback (most recent call last):
  File "/home/aria-ops-adapter-user/src/app/app/adapter.py", line 27, in <module>
    from sseapiclient import APIClient
ModuleNotFoundError: No module named 'sseapiclient'"

18:30:14,771 vmware_aria_operations_integration_sdk.describe ERROR adapterDefinition endpoint returned 500.
18:30:15,114 urllib3.connectionpool DEBUG http://localhost:None "POST /v1.43/containers/0965a5c10288bfc9e71acd8b537f57e846ac72e418bd8188b0af011668a45154/kill HTTP/1.1" 204 0
18:30:15,124 urllib3.connectionpool DEBUG http://localhost:None "GET /v1.43/containers/0965a5c10288bfc9e71acd8b537f57e846ac72e418bd8188b0af011668a45154/stats?stream=False HTTP/1.1" 200 None
18:30:15,134 urllib3.connectionpool DEBUG http://localhost:None "DELETE /v1.43/containers/0965a5c10288bfc9e71acd8b537f57e846ac72e418bd8188b0af011668a45154?v=False&link=False&force=False HTTP/1.1" 204 0
18:30:15,151 urllib3.connectionpool DEBUG http://localhost:None "POST /v1.43/images/prune?filters=%7B%22label%22%3A+%5B%22mp-test%22%5D%7D HTTP/1.1" 200 None
18:30:15,278 urllib3.connectionpool DEBUG http://localhost:None "POST /v1.43/images/prune?filters=%7B%22label%22%3A+%5B%22mp-test%22%5D%7D HTTP/1.1" 200 None
18:30:15,289 vmware_aria_operations_integration_sdk.mp_test ERROR Expecting value: line 1 column 1 (char 0)
